services:
  crud-mahasiswa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    volumes:
      - .:/app
      - /app/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
